FROM confluentinc/cp-kafka:6.1.1

ADD kafka_broker.yml /usr/app/kafka_broker.yml
ADD prom-jmx-agent-config.yml /usr/app/prom-jmx-agent-config.yml
ADD jmx_prometheus_javaagent-0.15.0.jar /usr/app/jmx_prometheus_javaagent.jar
